name: Send Email Notification After Workflow

on:
  workflow_run:
    workflows: ["workflow name"]
    types:
      - completed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download the artifact from the previous workflow
      - name: Download commit logs artifact
        uses: actions/download-artifact@v4
        with:
          name: commit-logs
          path: ./generated_docs

      # Step 3: Send the email
      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: GitHub Actions <no-reply@github.com>
          to: abdelghaniyacine.barka@outlook.com
        #   cc: mohamed.berhab@datamasterai.com,abdellah.bouchareb@datamasterai.com
          subject: GitHub Actions Notification
          html_body: file://.github/scripts/email_template.html
          attachments: ./generated_docs/*