name: Create Release Notes

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow GitHub Actions to create releases
      issues: write     # Allow writing to issues (for changelog generation)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-generate Release Notes
        id: generate_changelog
        uses: googleapis/release-please-action@v3
        with:
          release-type: github
          changelog-types: '["feat", "fix", "docs", "style", "refactor", "perf", "test", "chore"]'  # Use JSON array format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.generate_changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}