name: Create release

on:
  push:
    branches:
      - '*'  # Trigger on push to main branch

permissions:
  contents: write

jobs:
  release:
    name: Release on push to main
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Unique Tag
        id: create_tag
        run: |
          # Set the new tag version (you can modify this logic for versioning)
          TAG="v$(date +'%Y.%m.%d.%H%M%S')"  # Example tag format (year.month.day.hourminute.second)
          
          # Check if the tag already exists
          if git show-ref --tags | grep -q "refs/tags/$TAG"; then
            echo "Tag $TAG already exists. Exiting..."
            exit 1
          fi
          
          # Create the new tag and push it to the remote repository
          git tag $TAG
          git push origin $TAG  # Push the new tag to the remote repository
          echo "::set-output name=tag::$TAG"  # Set the tag as an output to use later

      - name: Create release with GitHub changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_tag.outputs.tag }}  # Use the created tag from the previous step
        run: |
          # Generate the changelog using GitHub CLI and capture it
          changelog=$(gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes)  # Generate the changelog notes

          echo "Changelog generated for release $tag:"
          echo "$changelog"

          # Create the release with the generated changelog notes in the release body
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --notes "$changelog"  # Use the generated changelog as the release notes