name: Create release

on:
  push:
    branches:
      - '*'  # Trigger on push to main branch

permissions:
  contents: write

jobs:
  release:
    name: Release on push to main
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Unique Tag
        id: create_tag
        run: |
          # Generate a tag based on the current timestamp
          TAG="v$(date +'%Y.%m.%d.%H%M%S')"
          
          # Check if the tag already exists remotely
          if gh release view "$TAG" --repo="$GITHUB_REPOSITORY" > /dev/null 2>&1; then
            echo "Tag $TAG already exists remotely. Exiting..."
            exit 1
          fi

          # Create and push the tag to remote
          git tag $TAG
          git push origin $TAG
          echo "::set-output name=tag::$TAG"  # Pass tag as an output

      - name: Generate Changelog Dynamically
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_tag.outputs.tag }}  # Get the tag from previous step
        run: |
          # Get the previous tag name (e.g., v2024.11.28.140000)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 "$tag^")
          
          # Fetch commits between the previous and current tag
          COMMITS=$(git log --pretty=format:"%s" "$PREVIOUS_TAG".."$tag")

          # Initialize changelog
          changelog="### What's Changed\n"

          # Loop over commits and filter by type (e.g., feat, style, etc.)
          for commit in $COMMITS; do
            # Check for commit types (e.g., feat, style)
            if [[ $commit =~ ^(feat|style|fix|docs|chore)\((.*)\):\ (.*) ]]; then
              type=${BASH_REMATCH[1]}  # commit type (feat, style, etc.)
              scope=${BASH_REMATCH[2]}  # scope of the change (e.g., API, GitHub)
              description=${BASH_REMATCH[3]}  # commit description
              changelog+="$type($scope): $description by @${GITHUB_ACTOR} in #${GITHUB_SHA}\n"
            else
              changelog+="$commit by @${GITHUB_ACTOR} in #${GITHUB_SHA}\n"
            fi
          done

          # Save changelog to output
          echo "::set-output name=changelog::$changelog"

      - name: Create Release with Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          changelog: ${{ steps.generate_changelog.outputs.changelog }}
          tag: ${{ steps.create_tag.outputs.tag }}  # Tag from the previous step
        run: |
          # Create the release with the dynamically generated changelog
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --notes "$changelog"  # Use dynamically generated changelog