name: Create Release Notes

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow GitHub Actions to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install github_changelog_generator --user-install  # Install for the current user

      - name: Add the Ruby bin directory to PATH
        run: echo "$HOME/.gem/ruby/3.0.0/bin" >> $GITHUB_PATH  # Ensure that the gem executables are in PATH

      - name: Generate Changelog
        id: changelog
        run: |
          github_changelog_generator --token ${{ secrets.GITHUB_TOKEN }} --unreleased
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            ## Changelog
            ${{ steps.changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}