name: Generate Commit Document

on:
  push:
    branches:
      - '*'  # Trigger on merges to the main branch
    #   - main  # Trigger on merges to the main branch

jobs:
  generate-doc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: pip install -r requirements.txt || true

      # Step 4: Run the script to generate the commit document
      - name: Generate Commit Document
        run: python generate_commit_doc.py

      # Step 5: Upload the generated commit document as an artifact
      - name: Upload Commit Document
        uses: actions/upload-artifact@v3
        with:
          name: commit-document
          path: generated_docs/commit_document.txt