name: Generate Commit Log

on:
  push:
    branches:
      - '*'  # or any other branches you want to trigger the action for
  workflow_dispatch:
    inputs:
      repo_owner:
        description: 'GitHub Username'
        required: true
        default: 'your-username'  # Optional default
      repo_name:
        description: 'GitHub Repository Name'
        required: true
        default: 'your-repository'  # Optional default

jobs:
  generate-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch and generate commit log
        run: |
          python .github/scripts/generate_commit_doc.py "${{ github.event.inputs.repo_owner }}" "${{ github.event.inputs.repo_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}