name: Generate Commit Log

on:
  push:
    branches:
      - '*'  # Trigger on all branches

#on:
#  push:
#    tags:
#      - 'v*'  # Only triggers on tags starting with 'v'

jobs:
  generate-commit-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install GitPython
          pip install PyGithub

      - name: Create the generated_docs directory
        run: mkdir -p generated_docs

      - name: Run the commit log generation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG_NAME: ${{ github.ref_name }}  # Get the tag name that triggered the workflow
        run: python .github/scripts/changelogs/main.py

      - name: Check the generated commit logs
        run: |
          echo "Checking generated_docs directory contents:"
          ls -la generated_docs

      - name: Upload all commit logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: commit-logs
          path: generated_docs/*