name: Generate Commit Log

on:
  push:
    branches:
      - '*'

jobs:
  generate-commit-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run the commit log generation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}  # Set owner as environment variable
          REPO_NAME: ${{ github.event.repository.name }}  # Set repo name as environment variable
        run: python .github/scripts/generate_commit_doc.py

      - name: Upload commit log as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: commit-log
          path: generated_docs/commit_document.md