name: Send Email Notification After Workflow

on:
  workflow_run:
    workflows: ["Validate Commit Message and Check GitHub Actions Changes on PR"]
    types:
      - completed

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3


      # Step 5: Send the email
      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: GitHub Actions <no-reply@github.com>
          to: yacinobatlm13@gmail.com
          subject: GitHub Actions Notification
          html_body: file://.github/scripts/email_template.html    